#!/usr/bin/env python3
"""Clawd ondeando la bandera — datos de la animacion. El motor vive en `animar_pixel.py`.

Clawd sostiene una bandera a cuadros que sube y ondea; el cuerpo se mece al
reves que la tela. Es "The Flag Waver" del articulo de Codrops
"Reverse-Engineering Claude AI's Mascot Animations with SVG and GSAP"
(Ayotomiwa Wale-Durojaye, mayo 2026), demo en ayotomcs.me/claude-mascot.

Reemplaza a la bandera anterior, borrada el 16/09/2026 por estar mal hecha.

De donde salieron estos datos
-----------------------------
Del codigo de la demo (modulo 4030), capturado con `capturar_gsap.js` y el GSAP
real, cada 70 ms:

- 12 telas dibujadas en reticula de 5 px. Cuadros 0-2: la tela sube. Cuadros
  3-11: ondea en bucle (la subida no se repite).
- Por cuadro, del codigo: balanceo del cuerpo [0,0,-5,-5,0,4,4,4,0,0,-5,-5] px,
  mano [0,-6,-12,-14,-8,-2,0,0,-4,-10,-16,-18] px y mano izquierda
  [0,0,4,4,0,0,0,0,0,0,4,4] px.

Dos capas, dos reticulas
------------------------
El cuerpo va en U = 16/3 px (bdy en x = 21.66, suelo en y = 146). La tela va en
su propia reticula de 5 px con 1 celda = 1U. Si la tela se muestreara en U, el
damero de 5 px haria muaré: cada ~15 celdas se duplicaria o perderia un cuadro.
La tela se ancla por el asta a la posicion real de la mano en cada cuadro, asi
que sigue pegada a la muneca.

Salidas
-------
- clawd-bandera: solo el bucle, 9 cuadros x 70 ms = 0.63 s. Para GIF, web y
  todo lo que se repite.
- clawd-bandera-con-subida: la subida una vez + 6 vueltas (4.2 s). Para video,
  que no se repite solo.

Colores: cuerpo y ojos canonicos; el blanco del damero es el de la demo.
Los ojos son "^ ^" (contento), dibujo de la demo.

Leyenda: .  transparente   #  naranja   @  negro   w  blanco
"""
import pathlib
import sys

from animar_pixel import componer, construir, verificar

PALETA = {
    '#': (217, 119, 87),    # d97757  cuerpo
    '@': (20, 20, 19),      # 141413  ojos, asta y cuadros negros
    'w': (255, 255, 255),   # ffffff  cuadros blancos (de la demo)
}

LIENZO = (34, 31)           # en U. La ultima fila apoya en el suelo.
ESCALA = 16
TIEMPO_MS = 70
FPS_VIDEO = 100

# --------------------------------------------------------------------------
# PIEZAS  cada una transcrita una vez, en reposo
# --------------------------------------------------------------------------

# patas de abajo: no se mecen (los pies quedan plantados)
PATAS_BAJAS = (0, """
##..##....##..##
##..##....##..##
""")

# cuerpo, ojos "^ ^" y patas de arriba. Las dos ultimas filas se fijaron a mano
# por medicion: en la fuente las 4 patas son rectangulos identicos de 11 px, y
# la de la derecha caia a media celda.
CUERPO = (0, """
################
################
##@@########@@##
#@##@######@##@#
################
################
################
################
################
################
################
################
##..##....##..##
##..##....##..##
""")

MANO_IZQ = (0, """
####
####
####
####
""")

MANO_DER = (0, """
####
####
####
####
""")

# 12 telas en su reticula de 5 px (1 celda = 1U), misma caja; el asta en la columna ASTA
T00 = (0, """
....................
....................
.........@w@........
.........@@w@.......
.........@w@w@......
.........@@w@w@.....
.........@w@w@w@....
.........@@w@w@w@...
.........@..w@w@w...
.........@...w@w@...
.........@....w@w...
.........@.....w@...
...............w....
""")

T01 = (0, """
....................
....................
.........@w@w@w.....
.........@@w@w@w....
.........@w@w@w@w...
.........@@w@w@w@w@w
.........@w@w@w@w@w@
.........@@w@w@w@w@w
.........@.....@w@w@
.........@......@w@w
.........@.......@w@
.........@..........
....................
""")

T02 = (0, """
....................
....................
.........@w@w@w.....
.........@@w@w@w@...
.........@w@w@w@w@w@
.........@@w@w@w@w@w
.........@w@w@w@w@w@
.........@@w@w@w@w@w
.........@.....@w@w@
.........@.......w@w
.........@..........
.........@..........
....................
""")

T03 = (0, """
....................
....................
.......@w@@.........
.......w@@w@w.......
.......ww@@w@w@w....
.......w@@w@w@w@....
.......@w@@w@w@w....
.......w@@w@w@w@....
.........@@w@w@w....
.........@...@w@....
.........@..........
.........@..........
....................
""")

T04 = (0, """
....................
....................
.....@w@w@..........
...w@w@w@@..........
..w@w@w@w@..........
..@w@w@w@@..........
..w@w@w@w@..........
..@w@w@w@@..........
..w@w....@..........
..@w@....@..........
...@w....@..........
.........@..........
....................
""")

T05 = (0, """
....................
....................
....w@w@w@..........
@w@w@w@w@@..........
w@w@w@w@w@..........
@w@w@w@w@@..........
w@w@w@w@w@..........
@w@w@w@w@@..........
w@w@.....@..........
.w.......@..........
.........@..........
.........@..........
....................
""")

T06 = (0, """
....................
@w@.................
w@w@w@w@w@..........
@w@w@w@w@@..........
w@w@w@w@w@..........
@w@w@w@w@@..........
w@w@w@w@w@..........
....@w@w@@..........
.........@..........
........@...........
........@...........
........@...........
....................
""")

T07 = (0, """
...w@...............
...@w@w@............
...w@w@w@@w.........
...@w@w@w@@.........
...w@w@w@@w.........
...@w@w@w@@.........
.....w@w@@w.........
........w@@.........
.........@..........
.........@..........
.........@..........
.........@..........
....................
""")

T08 = (0, """
....................
....................
.........@@w@.......
.........@w@w@......
.......@w@@w@w......
.......w@@w@w@......
.......@w@@w@w......
.......w@@w@w@......
.......@w@@w@.......
.......w@@w@........
.........@..........
.........@..........
....................
""")

T09 = (0, """
....................
....................
.........@w@w.......
.........@@w@w@w....
.........@w@w@w@w...
.........@@w@w@w@...
.........@w@w@w@w...
.........@@w@w@w@...
.........@...@w@w...
.........@...@w@@...
.........@...w@w@...
.........@...@w@....
....................
""")

T10 = (0, """
....................
....................
.........@w@w@w.....
.........@@w@w@w....
.........@w@w@w@w...
.........@@w@w@w@w@w
.........@w@w@w@w@w@
.........@@w@w@w@w@w
.........@.....@w@w@
.........@......@w@w
.........@.......@w@
.........@..........
....................
""")

T11 = (0, """
....................
....................
.........@w@w@w.....
.........@@w@w@w@...
.........@w@w@w@w@w@
.........@@w@w@w@w@w
.........@w@w@w@w@w@
.........@@w@w@w@w@w
.........@.....@w@w@
.........@.......w@w
.........@..........
.........@..........
....................
""")

TELAS = [T00, T01, T02, T03, T04, T05, T06, T07, T08, T09, T10, T11]
ASTA = 9

# posicion en reposo (columna, fila) dentro del lienzo
POS_BAJAS = (6, 29)
POS_CUERPO = (6, 15)
POS_MANO_IZQ = (2, 21)
POS_MANO_DER = (19, 12)
POS_ASTA = (21, 1)    # columna del asta y fila superior de la tela

# por cuadro: (balanceo del cuerpo, mano derecha, mano izquierda hacia abajo, tela)
# en celdas. De la demo en px: balanceo [0,0,-5,-5,0,4,4,4,0,0,-5,-5],
# mano [0,-6,-12,-14,-8,-2,0,0,-4,-10,-16,-18], mano izq [0,0,4,4,0,0,0,0,0,0,4,4],
# redondeados a celdas enteras (U = 16/3 px).
SUBIDA = [
    (0, 0, 0, 0),
    (0, -1, 0, 1),
    (-1, -2, 1, 2),
]
BUCLE = [
    (-1, -3, 1, 3),
    (0, -2, 0, 4),
    (1, 0, 0, 5),
    (1, 0, 0, 6),
    (1, 0, 0, 7),
    (0, -1, 0, 8),
    (0, -2, 0, 9),
    (-1, -3, 1, 10),
    (-1, -3, 1, 11),
]


def cuadro(sway, mano, izq, tela):
    capas = [
        (PATAS_BAJAS, *POS_BAJAS),
        (CUERPO, POS_CUERPO[0] + sway, POS_CUERPO[1]),
        (MANO_IZQ, POS_MANO_IZQ[0] + sway, POS_MANO_IZQ[1] + izq),
        (MANO_DER, POS_MANO_DER[0] + sway + mano, POS_MANO_DER[1]),
        (TELAS[tela], POS_ASTA[0] + sway + mano - ASTA, POS_ASTA[1]),
    ]
    return componer(LIENZO, capas)


def cuadros(entrada):
    """(poses, secuencia). entrada=False: solo el bucle. True: subida + 6 vueltas."""
    movs = (SUBIDA + BUCLE * 6) if entrada else BUCLE
    poses, secuencia, claves = {}, [], {}
    for m in movs:
        if m not in claves:
            claves[m] = f'f{len(claves):02d}'
            poses[claves[m]] = cuadro(*m)
        secuencia.append((claves[m], 1))
    return poses, secuencia


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1].startswith('-'):
        print(__doc__ + "\nUso:  python clawd_bandera.py CARPETA_DESTINO")
        sys.exit(0)
    destino = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else 'salida')
    for nombre, entrada in [('clawd-bandera', False), ('clawd-bandera-con-subida', True)]:
        poses, secuencia = cuadros(entrada)
        orden, medida, lienzo = construir(
            destino, poses, secuencia, PALETA, nombre=nombre, lienzo=LIENZO,
            escala=ESCALA, tiempo_ms=TIEMPO_MS, fps_video=FPS_VIDEO)
        print(nombre, '· fotogramas unicos:', len(orden), '· medida:', medida,
              '· duracion:', len(secuencia) * TIEMPO_MS / 1000, 's')
        try:
            malos = verificar(destino, nombre, orden, ESCALA)
            print('SVG infieles:', malos or 'ninguno')
        except (ImportError, OSError):
            print('SVG sin verificar (falta cairosvg o su libreria Cairo)')
