#!/usr/bin/env python3
"""Clawd con confeti — datos de la animacion. El motor vive en `animar_pixel.py`.

De donde salio
--------------
Replica de "Confetti Claude", del articulo de Codrops "Reverse-Engineering
Claude AI's Mascot Animations with SVG and GSAP" (Ayotomiwa Wale-Durojaye,
mayo 2026) y su demo en ayotomcs.me/claude-mascot. No se midio de un video: se
extrajo el componente SVG de la demo (rectangulos + linea de tiempo GSAP), se
ejecuto en Node y se transcribio cada dibujo a la reticula de Clawd.

Lo que se midio
---------------
- Reticula del personaje: U = 16/3 px. Cuerpo 16U, banda de brazos 24U, ojos y
  patas 2U: la MISMA reticula que `clawd_caminando.py`. Por eso el lienzo del
  personaje es de 28 columnas y las patas caen en las columnas 6-21 igual que
  en la caminata.
- Suelo: y = 113 px en la demo. La ultima fila de cada pose apoya ahi, salvo A2
  y B2, que despegan 1U (es el brinco del pisoton).
- El confeti vive en su propia reticula de 5 px; aqui 1 celda = 1U.
- La demo desplaza los cuadros levantados 2 px (0.375U) respecto al agachado.
  Se ignoro: en pixel art no hay media celda, y asi los pies no brincan.
- Agachado: los largos medidos (patas 2.25U, cuerpo bajo 1.1U, brazos 4.3U,
  ojos 2.06U, cuerpo alto 4.69U) se redondearon por segmento; suman 14U.
- Los cuadros 5-7 de la demo son `matrix(-1 ...)` de los 1-3: espejo exacto.
  Se verifico contra una transcripcion independiente de esos cuadros: todas las
  filas en que discrepaban eran ruido de fase de la transcripcion espejo.

El error de la demo que NO se copio
-----------------------------------
El articulo dice "ocho cuadros a 125 ms". La demo pone el ultimo `set()` en
t = 0.875 s, asi que la linea de tiempo dura 0.875 s y el cuadro 8 (B3) nunca
se ve: el pisoton izquierdo queda con 2 cuadros y el derecho con 3. Aqui el
ciclo es el de diseno: 8 cuadros de 125 ms = 1 s, simetrico.

Ritmo
-----
- Personaje: AGACHADO A1 A2 A3 AGACHADO B1 B2 B3, un tiempo cada uno.
- Rafaga 1 (derecha): arranca 1 cuadro tarde, cuando la mano ya esta arriba.
- Rafaga 2 (izquierda): arranca 6 cuadros tarde, con el otro brazo arriba. Es
  el espejo de la rafaga 1.
- Cada rafaga recorre 8 dibujos C0-C7 y sube y baja con ALTURA_RAFAGA.

Leyenda de la rejilla
---------------------
    .  transparente      #  naranja cuerpo      @  ojo
    n  confeti naranja   a  confeti azul        r  confeti rosa
"""
import pathlib
import sys

from animar_pixel import componer, construir, espejo, verificar

# Cuerpo y ojo: hex canonicos de Clawd (la demo usaba #DD775B, aproximado a ojo).
# Confeti: los hex declarados en el codigo de la demo. #CB708F y #C87392 son el
# mismo rosa con 3 unidades de diferencia; se unifican en el primero que aparece.
PALETA = {
    '#': (217, 119, 87),    # d97757  cuerpo
    '@': (20, 20, 19),      # 141413  ojo
    'n': (221, 131, 97),    # dd8361  confeti naranja
    'a': (124, 164, 208),   # 7ca4d0  confeti azul
    'r': (200, 115, 146),   # c87392  confeti rosa
}

LIENZO = (40, 36)           # en U. La fila 35 apoya en el suelo.
PERSONAJE_DX, PERSONAJE_DY = 6, 10   # el lienzo de 28x26 del personaje, centrado
RAFAGA_DX = 24              # columna de la rafaga derecha; la izquierda es su espejo
# fila superior de la rafaga por cuadro. De la demo: [-65,-72,-76,-70,-58,-42,-22,0] px
ALTURA_RAFAGA = [3, 1, 1, 2, 4, 7, 11, 15]

# --------------------------------------------------------------------------
# PERSONAJE  (fila_inicial, rejilla) sobre un lienzo de 28 x 26 U
# --------------------------------------------------------------------------

AGACHADO = (12, """
......################......
......################......
......################......
......################......
......################......
......##@@########@@##......
......##@@########@@##......
..########################..
..########################..
..########################..
..########################..
......################......
......##..##....##..##......
......##..##....##..##......
""")

A1 = (5, """
.....................####...
.....................####...
..............###########...
..........###############...
......############@@#####...
......############@@#####...
......##@@############......
......##@@############......
..####################......
..####################......
..####################......
..####################......
..####################......
......################......
......################......
......########..##..##......
......##..##....##..##......
......##..##....##..##......
......##..##....##..##......
......##..##....##..##......
......##..##....##..##......
""")

A2 = (3, """
......................###...
......................###...
.....................####...
.............############...
..........###############...
......############@@####....
......############@@##......
......##@@############......
......##@@############......
......################......
......################......
..####################......
..####################......
..####################......
..####################......
..####################......
......########..##..##......
......##..##....##..##......
......##..##....##..##......
......##..##....##..##......
......##..##....##..##......
......##..##................
""")

A3 = (5, """
.....................####...
.....................####...
..............###########...
..........###############...
......############@@#####...
......############@@#####...
......##@@############......
......##@@############......
..####################......
..####################......
..####################......
..####################......
..####################......
......################......
......################......
......########..##..##......
......##..##....##..##......
......##..##....##..##......
......##..##....##..##......
......##..##....##..##......
......##..##................
""")

# el pisoton del otro lado es el espejo exacto: no se dibuja, se voltea
B1, B2, B3 = (espejo(p) for p in (A1, A2, A3))
PERSONAJE = [AGACHADO, A1, A2, A3, AGACHADO, B1, B2, B3]

# --------------------------------------------------------------------------
# CONFETI  8 dibujos de 15 x 15 U, de disperso a vacio
# --------------------------------------------------------------------------

C0 = (0, """
..nn...r.......
......r........
...............
a..r...........
a..r...n.......
......n........
.a.............
..a............
...............
...............
...............
...............
...............
...............
...............
""")

C1 = (0, """
....nn....rr...
...............
a...r..........
.a...r.........
...............
........nn.....
...............
...aa..........
...........a...
............a..
...............
...............
...............
...............
...............
""")

C2 = (0, """
......n........
.....n.........
...........r...
............r..
.....rr........
aa.............
........n......
.........n.....
...............
...............
............a..
...............
...............
...............
...............
""")

C3 = (0, """
.....n.........
.....n.........
...............
.....r.........
....r..........
a.........nn...
...............
...............
..a............
...............
...............
...............
...............
...............
...............
""")

C4 = (0, """
.....n.........
......n........
...............
...............
....r..........
a..............
...............
...............
...............
...............
..............a
...............
...............
...............
...............
""")

C5 = (0, """
...n...........
...............
..............r
...............
...............
...............
...............
...............
a..............
...............
.............a.
...............
...............
...............
...............
""")

C6 = (0, """
n..............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
""")

C7 = (0, """
r..............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
...............
""")

CONFETI = [C0, C1, C2, C3, C4, C5, C6, C7]


def cuadro(t):
    """Cuadro t del ciclo: personaje + rafaga derecha (t-1) + izquierda (t-6)."""
    w = LIENZO[0]
    capas = [(PERSONAJE[t], PERSONAJE_DX, PERSONAJE_DY)]
    r1 = (t - 1) % 8
    capas.append((CONFETI[r1], RAFAGA_DX, ALTURA_RAFAGA[r1]))
    r2 = (t - 6) % 8
    capas.append((espejo(CONFETI[r2]), w - RAFAGA_DX - 15, ALTURA_RAFAGA[r2]))
    return componer(LIENZO, capas)


POSES = {f'f{t}': cuadro(t) for t in range(8)}
SECUENCIA = [(f'f{t}', 1) for t in range(8)]   # 8 x 125 ms = 1 s


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1].startswith('-'):
        print(__doc__ + "\nUso:  python clawd_confeti.py CARPETA_DESTINO")
        sys.exit(0)
    destino = sys.argv[1] if len(sys.argv) > 1 else 'salida'
    orden, medida, lienzo = construir(
        destino, POSES, SECUENCIA, PALETA,
        nombre='clawd-confeti', lienzo=LIENZO, escala=16, tiempo_ms=125,
        fps_video=24)
    print('fotogramas unicos:', len(orden), orden)
    print('medida por fotograma:', medida, '· lienzo en U:', lienzo)
    try:
        malos = verificar(pathlib.Path(destino), 'clawd-confeti', orden, 16)
        print('SVG infieles:', malos or 'ninguno')
    except (ImportError, OSError):
        print('SVG sin verificar (falta cairosvg o su libreria Cairo)')
