#!/usr/bin/env python3
"""Clawd caminando — datos de la animacion. El motor vive en `animar_pixel.py`.

De donde salieron estos numeros
-------------------------------
El video fuente es una captura de pantalla a 60 fps (704x464, 2.86 s). Midiendo
los bordes de color se recupera la reticula logica del sprite:

    U = 6.6875 px   unidad atomica del dibujo
    celda = 2 U     casi todo mide 2 U: el ojo, el ancho de una pata

El cuerpo NO se desplaza: su borde izquierdo esta clavado en x=296 px durante
todo el video (Clawd camina en el sitio y lo que se mueve es el fondo). Eso da
un ancla horizontal exacta. La vertical es la linea de suelo del fondo, que solo
baja con el scroll de la pagina. Con esas dos anclas cada fotograma cae en la
misma rejilla y las poses se pueden comparar entre si.

Cada bloque de la animacion se cuantizo tomando la MODA por celda de todos sus
fotogramas: asi se cae el ruido de compresion de WhatsApp sin tocar el dibujo.
Verificacion cruzada: el ciclo derecho resulto ser el espejo exacto del
izquierdo, celda por celda. IoU final contra el original: 0.973 — lo que falta
es el borde antialiaseado de la captura, que es justo lo que no se quiere copiar.

Cadencia medida: 5 fotogramas de video por tiempo => 12 fps. Las poses de apoyo
duran 2 tiempos y las de paso 1.

Metodo completo para hacer una animacion nueva: `references/animacion-pixel.md`.

Leyenda de la rejilla
---------------------
    .  transparente      #  naranja cuerpo
    %  naranja sombra    @  ojo
"""
import sys

from animar_pixel import construir, espejo, verificar

# La captura venia en #d46c4d por la compresion; aqui van los hex reales. La
# sombra es el naranja x0.85, que es la razon exacta medida entre las dos tintas.
PALETA = {
    '#': (217, 119, 87),    # d97757  cuerpo
    '%': (184, 101, 74),    # b8654a  sombra
    '@': (20, 20, 19),      # 141413  ojo
}

LIENZO = (28, 20)           # en unidades U. La fila 19 apoya en el suelo.

# --------------------------------------------------------------------------
# POSES  (fila_inicial, rejilla) — transcritas del video, ruido ya limpiado.
# La fila_inicial es el rebote: el cuerpo sube y baja 1 U sin redibujarse.
# --------------------------------------------------------------------------

QUIETO = (4, """
......################......
......################......
......##@@########@@##......
......##@@########@@##......
..########################..
..########################..
..########################..
..########################..
......################......
......################......
......################......
......################......
......##..##....##..##......
......##..##....##..##......
......##..##....##..##......
......##..##....##..##......
""")

PARPADEO = (5, """
......################......
......################......
......################......
......##@@@######@@@##......
..########################..
..########################..
..########################..
..########################..
......################......
......################......
......################......
......################......
......##..##....##..##......
......##..##....##..##......
......##..##....##..##......
""")

FRENTE = (5, """
......################......
......################......
......##@@########@@##......
......##@@########@@##......
..########################..
..########################..
..########################..
..########################..
......################......
......################......
......################......
.....##################.....
.....##..##......##..##.....
.....##..###....###..##.....
.....##...##....##...##.....
""")

# ciclo de caminata, version "gira a un lado". El otro lado es el espejo exacto.
A1 = (3, """
......%%%#############......
......%%%#############......
......%%%##@@######@@#......
......%%%##@@######@@#......
..%%%####################...
..%%%####################...
..%%%####################...
..%%%####################...
......%%%#############......
......%%%#############......
......%%%#############......
......%%%#############......
......%%%#############......
......%%...##..##...##......
......%%%..##..##..###......
.......%%..##..##..##.......
...........##..##...........
""")

A2 = (4, """
......%%%#############......
......%%%#############......
......%%%##@@######@@#......
......%%%##@@######@@#......
..%%%####################...
..%%%####################...
..%%%####################...
..%%%####################...
......%%%#############......
......%%%#############......
......%%%#############......
......%%%#############......
.......%%..##..##..##.......
.......%%..##..##..##.......
.......%%..##..##..##.......
.......%%..##..##..##.......
""")

A3 = (5, """
......%%%#############......
......%%%#############......
......%%%##@@######@@#......
......%%%##@@######@@#......
..%%%####################...
..%%%####################...
..%%%####################...
..%%%####################...
......%%%#############......
......%%%#############......
......%%%#############......
......%%%#############......
......%%..##....##..##......
......%%%.###..###.###......
.......%%..##..##..##.......
""")

A4 = (3, """
..............########......
......%%%#############......
......%%%##########@@#......
......%%%##@@######@@####...
......%%%##@@############...
......%%%################...
......%%%################...
..%%%#################......
..%%%#################......
..%%%#################......
..%%%#################......
......%%%#############......
......%%%#############......
.......%%..##..##...###.....
.......%%..##..##....##.....
.......%%..##..##....##.....
.......%%..##..##...........
""")

A5 = (3, """
......%%%########...........
......%%%#############......
......%%%##@@#########......
..%%%######@@######@@#......
..%%%##############@@#......
..%%%#################......
..%%%#################......
......%%#################...
......%%#################...
......%%#################...
......%%##############%%%...
.....%%###############......
.....%%###############......
....%%%....##..##..##.......
....%%.....##..##..##.......
....%%.....##..##..##.......
...........##..##..##.......
""")

# el ciclo derecho es el espejo exacto del izquierdo: no se dibuja, se voltea
B1, B2, B3, B4, B5 = (espejo(p) for p in (A1, A2, A3, A4, A5))

POSES = {
    'quieto': QUIETO, 'parpadeo': PARPADEO, 'frente': FRENTE,
    'a1': A1, 'a2': A2, 'a3': A3, 'a4': A4, 'a5': A5,
    'b1': B1, 'b2': B2, 'b3': B3, 'b4': B4, 'b5': B5,
}

# --------------------------------------------------------------------------
# SECUENCIA  (pose, tiempos de 1/12 s) — tal cual se midio en el video
# --------------------------------------------------------------------------
SECUENCIA = [
    ('quieto', 5), ('parpadeo', 1),
    ('a1', 1), ('a2', 1), ('a3', 2), ('a4', 2), ('a3', 2), ('a5', 2),
    ('a3', 2), ('a1', 2),
    ('frente', 2),
    ('b1', 1), ('b2', 1), ('b3', 2), ('b4', 2), ('b3', 2), ('b5', 2), ('b3', 1),
]

# La grabacion corta antes del ultimo paso del ciclo derecho. Esta variante lo
# cierra y deja el bucle simetrico; se ve mejor en loop infinito.
SECUENCIA_SIMETRICA = SECUENCIA[:-1] + [('b3', 2), ('b1', 2)]


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1].startswith('-'):
        print(__doc__ + "\nUso:  python clawd_caminando.py CARPETA_DESTINO")
        sys.exit(0)
    destino = sys.argv[1] if len(sys.argv) > 1 else 'salida'
    orden, medida, lienzo = construir(
        destino, POSES, SECUENCIA, PALETA,
        nombre='clawd-caminando', lienzo=LIENZO, escala=16, tiempo_ms=80)
    print('fotogramas unicos:', len(orden), orden)
    print('medida por fotograma:', medida, '· lienzo en U:', lienzo)
    try:
        malos = verificar(__import__('pathlib').Path(destino),
                          'clawd-caminando', orden, 16)
        print('SVG infieles:', malos or 'ninguno')
    except (ImportError, OSError):
        print('SVG sin verificar (falta cairosvg o su libreria Cairo)')
